import { NextResponse } from 'next/server'
import { createClient } from '@supabase/supabase-js'
import puppeteer from 'puppeteer'

const supabaseAdmin = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
)

export async function POST(req: Request) {
  try {
    const { documentId } = await req.json()

    if (!documentId) {
      return NextResponse.json(
        { error: 'documentId is required' },
        { status: 400 }
      )
    }

    const { data: generatedDocument, error } = await supabaseAdmin
      .from('generated_documents')
      .select('*')
      .eq('id', documentId)
      .single()

    if (error || !generatedDocument) {
      return NextResponse.json(
        { error: 'Generated document not found' },
        { status: 404 }
      )
    }

    const content = generatedDocument.generated_content || {}

    const sectionsHtml = Array.isArray(content.sections)
      ? content.sections
          .map(
            (section: any) => `
              <section>
                <h2>${section.heading || 'قسم'}</h2>
                <p>${section.content || ''}</p>
              </section>
            `
          )
          .join('')
      : ''

    const recommendationsHtml = Array.isArray(content.recommendations)
      ? content.recommendations
          .map((item: string) => `<li>${item}</li>`)
          .join('')
      : ''

    const actionsHtml = Array.isArray(content.required_actions)
      ? content.required_actions
          .map((item: string) => `<li>${item}</li>`)
          .join('')
      : ''

    const html = `
      <!DOCTYPE html>
      <html lang="ar" dir="rtl">
        <head>
          <meta charset="UTF-8" />
          <style>
            body {
              font-family: Arial, Tahoma, sans-serif;
              direction: rtl;
              text-align: right;
              padding: 40px;
              color: #111827;
              line-height: 1.9;
            }

            h1 {
              font-size: 26px;
              margin-bottom: 8px;
              color: #0f172a;
            }

            .type {
              font-size: 14px;
              color: #475569;
              margin-bottom: 30px;
            }

            h2 {
              font-size: 18px;
              color: #0f172a;
              margin-top: 28px;
              border-bottom: 1px solid #e5e7eb;
              padding-bottom: 6px;
            }

            p {
              font-size: 14px;
              white-space: pre-line;
            }

            ul {
              padding-right: 22px;
            }

            li {
              margin-bottom: 8px;
              font-size: 14px;
            }

            .footer {
              margin-top: 40px;
              font-size: 12px;
              color: #64748b;
              border-top: 1px solid #e5e7eb;
              padding-top: 12px;
            }
          </style>
        </head>

        <body>
          <h1>${generatedDocument.title || 'مستند تشغيلي'}</h1>

          <div class="type">
            نوع المستند: ${generatedDocument.document_type || ''}
          </div>

          ${sectionsHtml}

          <section>
            <h2>التوصيات</h2>
            <ul>${recommendationsHtml}</ul>
          </section>

          <section>
            <h2>الإجراءات المطلوبة</h2>
            <ul>${actionsHtml}</ul>
          </section>

          <section>
            <h2>ملاحظات الاعتماد</h2>
            <p>${content.approval_notes || ''}</p>
          </section>

          <div class="footer">
            Generated by AI Operations Layer
          </div>
        </body>
      </html>
    `

    const browser = await puppeteer.launch({
      headless: true,
      args: ['--no-sandbox', '--disable-setuid-sandbox'],
    })

    const page = await browser.newPage()
    await page.setContent(html, {
  waitUntil: 'load',
})

    const pdfBuffer = await page.pdf({
      format: 'A4',
      printBackground: true,
      margin: {
        top: '20mm',
        right: '15mm',
        bottom: '20mm',
        left: '15mm',
      },
    })

    await browser.close()

   return new NextResponse(pdfBuffer as unknown as BodyInit, {
      status: 200,
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="${generatedDocument.document_type}.pdf"`,
      },
    })
  } catch (error: any) {
    console.error(error)

    return NextResponse.json(
      { error: error.message || 'PDF export failed' },
      { status: 500 }
    )
  }
}